spring.application.name=Food_Donation_Manager

spring.datasource.url=jdbc:sqlite:database.db?date_string_format=yyyy-MM-dd&foreign_keys=true
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true